require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe DicomseriesController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Dicomseries. As you add validations to Dicomseries, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DicomseriesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all dicomseries as @dicomseries" do
      dicomseries = Dicomseries.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:dicomseries)).to eq([dicomseries])
    end
  end

  describe "GET #show" do
    it "assigns the requested dicomseries as @dicomseries" do
      dicomseries = Dicomseries.create! valid_attributes
      get :show, params: {id: dicomseries.to_param}, session: valid_session
      expect(assigns(:dicomseries)).to eq(dicomseries)
    end
  end

  describe "GET #new" do
    it "assigns a new dicomseries as @dicomseries" do
      get :new, params: {}, session: valid_session
      expect(assigns(:dicomseries)).to be_a_new(Dicomseries)
    end
  end

  describe "GET #edit" do
    it "assigns the requested dicomseries as @dicomseries" do
      dicomseries = Dicomseries.create! valid_attributes
      get :edit, params: {id: dicomseries.to_param}, session: valid_session
      expect(assigns(:dicomseries)).to eq(dicomseries)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Dicomseries" do
        expect {
          post :create, params: {dicomseries: valid_attributes}, session: valid_session
        }.to change(Dicomseries, :count).by(1)
      end

      it "assigns a newly created dicomseries as @dicomseries" do
        post :create, params: {dicomseries: valid_attributes}, session: valid_session
        expect(assigns(:dicomseries)).to be_a(Dicomseries)
        expect(assigns(:dicomseries)).to be_persisted
      end

      it "redirects to the created dicomseries" do
        post :create, params: {dicomseries: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Dicomseries.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved dicomseries as @dicomseries" do
        post :create, params: {dicomseries: invalid_attributes}, session: valid_session
        expect(assigns(:dicomseries)).to be_a_new(Dicomseries)
      end

      it "re-renders the 'new' template" do
        post :create, params: {dicomseries: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested dicomseries" do
        dicomseries = Dicomseries.create! valid_attributes
        put :update, params: {id: dicomseries.to_param, dicomseries: new_attributes}, session: valid_session
        dicomseries.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested dicomseries as @dicomseries" do
        dicomseries = Dicomseries.create! valid_attributes
        put :update, params: {id: dicomseries.to_param, dicomseries: valid_attributes}, session: valid_session
        expect(assigns(:dicomseries)).to eq(dicomseries)
      end

      it "redirects to the dicomseries" do
        dicomseries = Dicomseries.create! valid_attributes
        put :update, params: {id: dicomseries.to_param, dicomseries: valid_attributes}, session: valid_session
        expect(response).to redirect_to(dicomseries)
      end
    end

    context "with invalid params" do
      it "assigns the dicomseries as @dicomseries" do
        dicomseries = Dicomseries.create! valid_attributes
        put :update, params: {id: dicomseries.to_param, dicomseries: invalid_attributes}, session: valid_session
        expect(assigns(:dicomseries)).to eq(dicomseries)
      end

      it "re-renders the 'edit' template" do
        dicomseries = Dicomseries.create! valid_attributes
        put :update, params: {id: dicomseries.to_param, dicomseries: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested dicomseries" do
      dicomseries = Dicomseries.create! valid_attributes
      expect {
        delete :destroy, params: {id: dicomseries.to_param}, session: valid_session
      }.to change(Dicomseries, :count).by(-1)
    end

    it "redirects to the dicomseries list" do
      dicomseries = Dicomseries.create! valid_attributes
      delete :destroy, params: {id: dicomseries.to_param}, session: valid_session
      expect(response).to redirect_to(dicomseries_index_url)
    end
  end

end
